#ifndef PYRITE_MODEL_MODELS_HH
#define PYRITE_MODEL_MODELS_HH

#include "compiler/compiler.hh"
#include "model/expr.hh"
#include "model/type.hh"
#include "model/block.hh"
#include "model/program.hh"
#include "model/functionargs.hh"
#include "model/function.hh"
#include "model/name.hh"
#include "model/callargs.hh"
#include "model/call.hh"
#include "model/class.hh"
#include "model/attribute.hh"
#include "model/methodcall.hh"
#include "model/new.hh"
#include "model/module.hh"
#include "model/while.hh"
#include "model/if.hh"
#include "model/binop.hh"
#include "model/integer.hh"
#include "model/double.hh"
#include "model/string.hh"
#include "model/bool.hh"
#include "model/nil.hh"
#include "model/assign.hh"
#include "model/return.hh"
#include "model/value.hh"

#endif
