.TH PROTY "1" "2011-06-25" "" "Proty Programmers Reference Guide"
.SH NAME
proty \- a dynamic, prototype based programming language
.SH SYNOPSIS
.B proty
[\-\-version] [\-c file] [\-g] [\-d]

.SH OPTIONS
.TP
.BI "\-c " file
write llvm bitcode to file
.TP
.B \-d
write llvm intermediate code to stdout
.TP
.B \-g
generate debug symbols
.TP
.B \-h, \-\-help
displays a compact option overview
.TP
.B \--version
display version information

.SH SEE ALSO
Official website:   http://www.proty.cc
.br
Documentation:      http://doc.proty.cc
