.TH PROTY "1" "2012-01-14" "" "Proty Programmers Reference Guide"
.SH NAME
proty \- a dynamic, prototype based programming language
.SH SYNOPSIS
.B proty
[
.B \-c
]
[
.B \-d
]
[
.B \-h
]
[
.B \-o
.I file
]
[
.B \-\-version
]
[
.B \-\-
]
[
.I input-file
]

.SH OPTIONS
.TP
.B \-c
compile to bytecode
.TP
.B \-d
dump bytecode to stdout
.TP
.B \-h, \-\-help
display a compact option overview
.TP
.BI "\-o " file
set the output filename
.TP
.B \--version
display version information

.SH SEE ALSO
Official website:   http://www.proty.cc
.br
Documentation:      http://doc.proty.cc
