.TH PROTY "1" "2011-08-07" "" "Proty Programmers Reference Guide"
.SH NAME
proty \- a dynamic, prototype based programming language
.SH SYNOPSIS
.B proty
[
.B \-\-version
]
[
.B \-c
.I file
]
[
.B \-g
]
[
.B \-d
]
[
.B \-\-
]
[
.I input-file
]

.SH OPTIONS
.TP
.B \-c
write compiled module to file
.TP
.B \-d
dump llvm intermediate code to stdout
.TP
.B \-g
generate debugging symbols
.TP
.B \-h, \-\-help
display a compact option overview
.TP
.BI "\-o " file
set the output file
.TP
.B \--version
display version information

.SH SEE ALSO
Official website:   http://www.proty.cc
.br
Documentation:      http://doc.proty.cc
